-- ============================================================================
-- capiTrade Database Schema
-- PostgreSQL + pgvector (Supabase)
--
-- Run this in the Supabase SQL editor (or via psql).
-- Order is important — extensions and tables are created before functions/indexes.
-- ============================================================================

-- ─── 0. Enable pgvector ──────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS vector;

-- ─── 1. Users ─────────────────────────────────────────────────────────────────
-- Supabase Auth manages authentication; this table extends the auth.users record.
CREATE TABLE IF NOT EXISTS public.users (
  id               UUID PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  email            TEXT NOT NULL,
  display_name     TEXT,
  virtual_balance  NUMERIC(12, 2) NOT NULL DEFAULT 10000.00,
  created_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.users IS 'Extended user profile. Extends auth.users with trading-specific fields.';

-- ─── 2. Trades ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.trades (
  id            UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id       UUID        NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  market        TEXT        NOT NULL CHECK (market IN ('Americas', 'Asia', 'MiddleEast')),
  amount        NUMERIC(12, 2) NOT NULL CHECK (amount >= 100),
  position      TEXT        NOT NULL CHECK (position IN ('BUY', 'SELL', 'HOLD')),
  entry_price   NUMERIC(12, 4) NOT NULL,
  exit_price    NUMERIC(12, 4),
  status        TEXT        NOT NULL DEFAULT 'active'
                  CHECK (status IN ('pending', 'active', 'completed', 'cancelled')),
  waiting_days  INTEGER     NOT NULL DEFAULT 3 CHECK (waiting_days IN (3, 7)),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS trades_user_id_idx    ON public.trades (user_id);
CREATE INDEX IF NOT EXISTS trades_status_idx     ON public.trades (status);
CREATE INDEX IF NOT EXISTS trades_created_at_idx ON public.trades (created_at DESC);

COMMENT ON TABLE public.trades IS 'User trading positions. Each row represents one trade with a 3- or 7-day hold period.';

-- ─── 3. Bot Decisions ─────────────────────────────────────────────────────────
-- The quantitative bot makes an independent decision for every user trade.
CREATE TABLE IF NOT EXISTS public.bot_decisions (
  id                UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  trade_id          UUID        NOT NULL REFERENCES public.trades (id) ON DELETE CASCADE,
  position          TEXT        NOT NULL CHECK (position IN ('BUY', 'SELL', 'HOLD')),
  confidence_score  NUMERIC(5, 4) CHECK (confidence_score BETWEEN 0 AND 1),
  technical_score   NUMERIC(5, 4) CHECK (technical_score  BETWEEN 0 AND 1),
  volatility_score  NUMERIC(5, 4) CHECK (volatility_score BETWEEN 0 AND 1),
  risk_reward_score NUMERIC(5, 4) CHECK (risk_reward_score BETWEEN 0 AND 1),
  reasoning         TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS bot_decisions_trade_id_idx ON public.bot_decisions (trade_id);

COMMENT ON TABLE public.bot_decisions IS 'Quantitative bot decisions. One row per trade. NOT generated by an LLM — pure formula.';

-- ─── 4. Conversations ─────────────────────────────────────────────────────────
-- Stores full message history for pre-trade and post-trade AI conversations.
CREATE TABLE IF NOT EXISTS public.conversations (
  id                       UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  trade_id                 UUID        NOT NULL REFERENCES public.trades (id) ON DELETE CASCADE,
  phase                    TEXT        NOT NULL CHECK (phase IN ('pre_trade', 'post_trade')),
  messages                 JSONB       NOT NULL DEFAULT '[]'::jsonb,
  reasoning_quality_score  NUMERIC(4, 2),  -- 0–10 score assigned by the AI coach
  created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (trade_id, phase)
);

CREATE INDEX IF NOT EXISTS conversations_trade_id_idx ON public.conversations (trade_id);

COMMENT ON TABLE public.conversations IS 'AI coaching conversation history. messages is a JSONB array of {role, content, timestamp}.';

-- ─── 5. User Metrics ──────────────────────────────────────────────────────────
-- Cached performance metrics. Recalculated after each completed trade.
CREATE TABLE IF NOT EXISTS public.user_metrics (
  id                    UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id               UUID        NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  total_trades          INTEGER     NOT NULL DEFAULT 0,
  win_rate              NUMERIC(5, 4) DEFAULT 0 CHECK (win_rate BETWEEN 0 AND 1),
  sharpe_ratio          NUMERIC(8, 4) DEFAULT 0,
  max_drawdown          NUMERIC(5, 4) DEFAULT 0 CHECK (max_drawdown BETWEEN 0 AND 1),
  avg_gain              NUMERIC(8, 4) DEFAULT 0,
  avg_loss              NUMERIC(8, 4) DEFAULT 0,
  reasoning_quality_avg NUMERIC(4, 2) DEFAULT 0,
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (user_id)
);

COMMENT ON TABLE public.user_metrics IS 'Cached performance dashboard values per user. Refreshed on each trade completion.';

-- ─── 6. Knowledge Base (pgvector RAG) ────────────────────────────────────────
-- Stores embeddings for:
--   • user_reasoning      — past trade reasoning submitted by users
--   • coaching_prompt     — pre-seeded Socratic question templates
--   • educational_content — short explanations of financial concepts
--
-- Embedding model: sentence-transformers/all-MiniLM-L6-v2 → 384 dimensions
-- (Change to 1536 if you switch to OpenAI text-embedding-3-small / ada-002)
CREATE TABLE IF NOT EXISTS public.knowledge_base (
  id         UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  content    TEXT        NOT NULL,
  embedding  VECTOR(384) NOT NULL,
  metadata   JSONB       NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- IVFFlat index for approximate nearest-neighbour search (cosine distance)
-- Increase `lists` proportionally as you add more rows (rule of thumb: rows/1000)
CREATE INDEX IF NOT EXISTS knowledge_base_embedding_idx
  ON public.knowledge_base
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 50);

CREATE INDEX IF NOT EXISTS knowledge_base_metadata_idx
  ON public.knowledge_base
  USING gin (metadata);

COMMENT ON TABLE public.knowledge_base IS 'Vector store for RAG. Holds user reasoning, coaching prompts, and educational content.';

-- ─── 7. Vector similarity search function ────────────────────────────────────
CREATE OR REPLACE FUNCTION public.match_documents (
  query_embedding  VECTOR(384),
  match_threshold  FLOAT,
  match_count      INT,
  filter           JSONB DEFAULT '{}'::jsonb
)
RETURNS TABLE (
  id         UUID,
  content    TEXT,
  metadata   JSONB,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    kb.id,
    kb.content,
    kb.metadata,
    1 - (kb.embedding <=> query_embedding) AS similarity
  FROM public.knowledge_base AS kb
  WHERE
    (filter = '{}'::jsonb OR kb.metadata @> filter)
    AND 1 - (kb.embedding <=> query_embedding) > match_threshold
  ORDER BY kb.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

COMMENT ON FUNCTION public.match_documents IS
  'Returns the top match_count knowledge base rows whose embeddings are most '
  'similar to query_embedding, filtered by metadata and a minimum similarity threshold.';

-- ─── 8. Auto-update triggers ──────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.handle_updated_at ()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER users_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE OR REPLACE TRIGGER conversations_updated_at
  BEFORE UPDATE ON public.conversations
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- ─── 9. New user initialisation trigger ──────────────────────────────────────
-- Automatically creates a public.users row when someone signs up via Supabase Auth.
CREATE OR REPLACE FUNCTION public.handle_new_user ()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.users (id, email)
  VALUES (NEW.id, NEW.email)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ─── 10. Row Level Security (RLS) ─────────────────────────────────────────────
ALTER TABLE public.users          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trades         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bot_decisions  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_metrics   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_base ENABLE ROW LEVEL SECURITY;

-- users: own row only
CREATE POLICY "users: select own"  ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "users: update own"  ON public.users FOR UPDATE USING (auth.uid() = id);

-- trades: own rows only
CREATE POLICY "trades: select own" ON public.trades FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "trades: insert own" ON public.trades FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "trades: update own" ON public.trades FOR UPDATE USING (auth.uid() = user_id);

-- bot_decisions: readable if trade belongs to user
CREATE POLICY "bot_decisions: select via trade"
  ON public.bot_decisions FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.trades t
      WHERE t.id = trade_id AND t.user_id = auth.uid()
    )
  );

-- conversations: readable if trade belongs to user
CREATE POLICY "conversations: select via trade"
  ON public.conversations FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.trades t
      WHERE t.id = trade_id AND t.user_id = auth.uid()
    )
  );

-- user_metrics: own row only
CREATE POLICY "user_metrics: select own" ON public.user_metrics FOR SELECT USING (auth.uid() = user_id);

-- knowledge_base: users can read own reasoning; all can read coaching/educational content
CREATE POLICY "knowledge_base: read coaching and educational"
  ON public.knowledge_base FOR SELECT
  USING (
    (metadata->>'type' IN ('coaching_prompt', 'educational_content'))
    OR (metadata->>'user_id' = auth.uid()::text)
  );

-- ─── 11. Seed data — Coaching Prompts ─────────────────────────────────────────
-- These are pre-loaded into the knowledge base as coaching_prompt type rows.
-- The embedding column is intentionally left as a zero vector here; in practice
-- you should generate real embeddings via the /api/seed endpoint or a script.
--
-- Uncomment and run AFTER the knowledge_base table is created.
-- Replace the zero vectors with real 384-dim embeddings from your embedding model.

/*
INSERT INTO public.knowledge_base (content, embedding, metadata) VALUES

-- Growth mindset / reflection prompts
('What specific data or indicators did you look at before making this decision?',
  array_fill(0::real, ARRAY[384])::vector(384),
  '{"type": "coaching_prompt", "confidence": "any", "tag": "evidence-seeking"}'::jsonb),

('Have you considered how this market has behaved during similar macroeconomic conditions in the past?',
  array_fill(0::real, ARRAY[384])::vector(384),
  '{"type": "coaching_prompt", "confidence": "low", "tag": "historical-context"}'::jsonb),

('What would need to happen for you to be wrong about this trade?',
  array_fill(0::real, ARRAY[384])::vector(384),
  '{"type": "coaching_prompt", "confidence": "high", "tag": "falsifiability"}'::jsonb),

('If you had to explain your reasoning to someone unfamiliar with this market, what would you say?',
  array_fill(0::real, ARRAY[384])::vector(384),
  '{"type": "coaching_prompt", "confidence": "any", "tag": "clarity"}'::jsonb),

('How does your confidence level compare with the actual amount you are investing?',
  array_fill(0::real, ARRAY[384])::vector(384),
  '{"type": "coaching_prompt", "confidence": "any", "tag": "position-sizing"}'::jsonb),

-- Educational content snippets
('The Sharpe Ratio measures return per unit of risk. A ratio above 1.0 is generally considered good, above 2.0 is excellent. It rewards consistent, risk-adjusted gains rather than lucky spikes.',
  array_fill(0::real, ARRAY[384])::vector(384),
  '{"type": "educational_content", "concept": "sharpe_ratio"}'::jsonb),

('RSI (Relative Strength Index) oscillates between 0 and 100. Values below 30 suggest the asset may be oversold (potential upside); above 70 suggests overbought (potential pullback). It does not predict direction — it indicates momentum extremes.',
  array_fill(0::real, ARRAY[384])::vector(384),
  '{"type": "educational_content", "concept": "rsi"}'::jsonb),

('A Simple Moving Average (SMA) smooths price data by calculating the average over a rolling window. When the short-term SMA (e.g. 20-day) crosses above the long-term SMA (e.g. 50-day), it is sometimes called a golden cross — a potential bullish signal.',
  array_fill(0::real, ARRAY[384])::vector(384),
  '{"type": "educational_content", "concept": "sma"}'::jsonb),

('Max Drawdown is the largest peak-to-trough decline in portfolio value. A 20% max drawdown means your portfolio fell 20% from its highest point before recovering. Professional investors watch this closely to understand worst-case losses.',
  array_fill(0::real, ARRAY[384])::vector(384),
  '{"type": "educational_content", "concept": "max_drawdown"}'::jsonb),

('Risk/Reward ratio compares how much you stand to gain against how much you could lose on a trade. A 3:1 ratio — risking $1 to potentially gain $3 — is a common minimum threshold used by professional traders.',
  array_fill(0::real, ARRAY[384])::vector(384),
  '{"type": "educational_content", "concept": "risk_reward"}'::jsonb);
*/

-- ─── End of schema ────────────────────────────────────────────────────────────
